name: Update Deps
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 10 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: markelliot/update-yarn-deps@v1
        with:
          push-to-repo-token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          commit-user: HyunseungLee-Travis
          commit-email: HyunseungLee-Travis@users.noreply.github.com
